title: Invoke-Obfuscation STDIN+ Launcher
id: 0c718a5e-4284-4fb9-b4d9-b9a50b3a1974
related:
    - id: 72862bf2-0eb1-11eb-adc1-0242ac120002
      type: derived
description: Detects Obfuscated use of stdin to execute PowerShell
status: experimental
author: Jonathan Cheong, oscd.community
date: 2020/10/15
modified: 2021/09/17
references:
     - https://github.com/Neo23x0/sigma/issues/1009 #(Task 25)
tags:
    - attack.defense_evasion
    - attack.t1027
    - attack.execution
    - attack.t1059.001
logsource:
    product: windows
    service: security
detection:
    selection_eventid:
        EventID: 4697
    selection:
        ServiceFileName|re: '.*cmd.{0,5}(?:\/c|\/r).+powershell.+(?:\$\{?input\}?|noexit).+\"'
    condition: selection and selection_eventid
falsepositives:
    - Unknown
level: high