title: Invoke-Obfuscation Via Use MSHTA
id: 9b8d9203-4e0f-4cd9-bb06-4cc4ea6d0e9a
related:
    - id: 7e9c7999-0f9b-4d4a-a6ed-af6d553d4af4
      type: derived
description: Detects Obfuscated Powershell via use MSHTA in Scripts
status: experimental
author: Nikita Nazarov, oscd.community
date: 2020/10/09
modified: 2021/09/18
references:
    - https://github.com/Neo23x0/sigma/issues/1009 #(Task31)
tags:
    - attack.defense_evasion
    - attack.t1027
    - attack.execution
    - attack.t1059.001
logsource:
    product: windows
    service: security
detection:
    selection_eventid:
        EventID: 4697
    selection:
        ServiceFileName|re: '(?i).*(set).*(&&).*(mshta).*(vbscript:createobject).*(\.run).*\(window\.close\).*"'
    condition: selection and selection_eventid
falsepositives:
    - Unknown
level: high