title: Cowrie - Logging Configuration Changes on Linux Host
id: 5f8f872f-6b61-4f3d-8f0e-6c1f2e5a2a47
related:
  - id: c830f15d-6f6e-430f-8074-6f73d6807841
    type: similar
status: experimental
description: Detect changes of syslog daemons configuration files
author: Saravanan Palanisamy
date: 2025-08-23
modified: 2025-08-23
tags:
  - attack.defense-evasion
  - attack.t1562.006
logsource:
  product: cowrie
  category: application
detection:
  selection:
    input|contains:
      - "/etc/syslog.conf"
      - "/etc/rsyslog.conf"
      - "/etc/syslog-ng/syslog-ng.conf"
  condition: selection
falsepositives:
  - Unlikely
level: high