title: Cowrie - Auditing Configuration Changes on Linux Host
id: d4b9970f-ec94-4f80-890a-84abcd660e73
status: experimental
description: Detect changes in auditd configuration files
references:
  - https://github.com/Neo23x0/auditd/blob/master/audit.rules
author: Saravanan Palanisamy
date: 2025-08-21
modified: 2025-08-21
tags:
  - attack.defense-evasion
  - attack.t1562.006
logsource:
  product: cowrie
  category: application
detection:
  selection:
    input|contains:
      - "/etc/audit/"
      - "/etc/libaudit.conf"
      - "/etc/audisp/"
  condition: selection
falsepositives:
  - Unlikely
level: high
