title: Potential Remote Services Abuse via Modification of VPN SSL Settings
id: 8b5dacf2-aeb7-459d-b133-678eb696d410
status: experimental
description: |
    Detects the modification of VPN SSL Settings (for example, the modification of authentication rules).
    This behavior was observed in pair with Potential Remote Services Abuse via Addition of VPN SSL Web Portal - Fortinet Fortigate Firewall (sigma rule)
references:
    - https://www.fortiguard.com/psirt/FG-IR-24-535
    - https://posts.inthecyber.com/exposed-fortinet-fortigate-firewall-interface-leads-to-lockbit-ransomware-cve-2024-55591-de8fcfb6c45c
author: Marco Pedrinazzi @pedrinazziM (InTheCyber)
date: 2025-02-14
tags:
    - attack.persistence
    - attack.initial-access
    - attack.t1133
logsource:
    product: fortinet
    service: event
detection:
    selection:
        action: 'Edit'
        cfgpath: 'vpn.ssl.settings'
    condition: selection
falsepositives:
    - VPN SSL settings can be changed for legitimate purposes
level: medium
