title: Unix Shell Configuration Modification
id: a94cdd87-6c54-4678-a6cc-2814ffe5a13d
related:
    - id: e74e15cc-c4b6-4c80-b7eb-dfe49feb7fe9
      type: obsolete
status: test
description: Detect unix shell configuration modification. Adversaries may establish persistence through executing malicious commands triggered when a new shell is opened.
references:
    - https://objective-see.org/blog/blog_0x68.html
    - https://web.archive.org/web/20221204161143/https://www.glitch-cat.com/p/green-lambert-and-attack
    - https://www.anomali.com/blog/pulling-linux-rabbit-rabbot-malware-out-of-a-hat
author: Peter Matkovski, IAI
date: 2023-03-06
modified: 2023-03-15
tags:
    - attack.privilege-escalation
    - attack.persistence
    - attack.t1546.004
logsource:
    product: linux
    service: auditd
detection:
    selection:
        type: 'PATH'
        name:
            - '/etc/shells'
            - '/etc/profile'
            - '/etc/profile.d/*'
            - '/etc/bash.bashrc'
            - '/etc/bashrc'
            - '/etc/zsh/zprofile'
            - '/etc/zsh/zshrc'
            - '/etc/zsh/zlogin'
            - '/etc/zsh/zlogout'
            - '/etc/csh.cshrc'
            - '/etc/csh.login'
            - '/root/.bashrc'
            - '/root/.bash_profile'
            - '/root/.profile'
            - '/root/.zshrc'
            - '/root/.zprofile'
            - '/home/*/.bashrc'
            - '/home/*/.zshrc'
            - '/home/*/.bash_profile'
            - '/home/*/.zprofile'
            - '/home/*/.profile'
            - '/home/*/.bash_login'
            - '/home/*/.bash_logout'
            - '/home/*/.zlogin'
            - '/home/*/.zlogout'
    condition: selection
falsepositives:
    - Admin or user activity is expected to generate some false positives
level: medium
simulation:
    - type: atomic-red-team
      name: Append to the system shell profile
      technique: T1546.004
      atomic_guid: 694b3cc8-6a78-4d35-9e74-0123d009e94b
    - type: atomic-red-team
      name: Append commands user shell profile
      technique: T1546.004
      atomic_guid: bbdb06bc-bab6-4f5b-8232-ba3fbed51d77
    - type: atomic-red-team
      name: Add command to .bash_profile
      technique: T1546.004
      atomic_guid: 94500ae1-7e31-47e3-886b-c328da46872f
    - type: atomic-red-team
      name: Add command to .bashrc
      technique: T1546.004
      atomic_guid: 0a898315-4cfa-4007-bafe-33a4646d115f
    - type: atomic-red-team
      name: System shell profile scripts
      technique: T1546.004
      atomic_guid: 8fe2ccfd-f079-4c03-b1a9-bd9b362b67d4
    - type: atomic-red-team
      name: Create/Append to .bash_logout
      technique: T1546.004
      atomic_guid: 37ad2f24-7c53-4a50-92da-427a4ad13f58
