title: UAC Bypass via ms-settings Registry Hijacking with PowerShell Execution
id: 889c8cb5-24a1-4616-b5c9-b1163f83e3b8
status: test
description: Detects UAC bypass attempts through registry hijacking of ms-settings protocol handler to execute malicious PowerShell commands, commonly used by Cobalt Strike and other implants for token duplication privilege escalation.
references:
  - https://thedfirreport.com/2025/09/29/from-a-single-click-how-lunar-spider-enabled-a-near-two-month-intrusion/
  - https://enigma0x3.net/2017/03/17/fileless-uac-bypass-using-sdclt-exe/
author: yxinmiracle
date: 2025-10-18
tags:
  - attack.defense_evasion
  - attack.privilege_escalation
  - attack.t1548.002
logsource:
  category: registry_event
  product: windows
detection:
  selection_registry:
    TargetObject|endswith: '\Software\Classes\ms-settings\shell\open\command'
  selection_commands:
    Details|contains|all:
      - 'cmd.exe'
      - 'powershell'
    Details|contains|any:
      - 'IEX'
      - 'DownloadString'
      - 'Net.WebClient'
      - 'nop'
      - 'w hidden'
      - 'windowstyle hidden'
      - 'encodedcommand'
  condition: selection_registry and selection_commands
falsepositives:
  - Unknown
level: high