title: UAC Bypass via MS-Settings Registry Hijacking with PowerShell Execution
id: 889c8cb5-24a1-4616-b5c9-b1163f83e3b8
status: experimental
description: Detects UAC bypass attempts through registry hijacking of ms-settings protocol handler to execute malicious PowerShell commands, commonly used by Cobalt Strike and other implants for token duplication privilege escalation.
references:
    - https://thedfirreport.com/2025/09/29/from-a-single-click-how-lunar-spider-enabled-a-near-two-month-intrusion/
    - https://enigma0x3.net/2017/03/17/fileless-uac-bypass-using-sdclt-exe/
author: yxinmiracle
date: 2025-10-18
tags:
    - attack.defense_evasion
    - attack.privilege_escalation
    - attack.t1548.002
logsource:
    category: registry_event
    product: windows
detection:
    selection_registry:
        TargetObject|endswith: '\Software\Classes\ms-settings\shell\open\command'
    base_components:
        Details|contains|all:
            - 'cmd.exe'
            - 'powershell'
    suspicious_indicators:
        Details|contains:
            - 'IEX'    # Invoke-Expression for code execution
            - 'DownloadString'    # Download content from remote sources
            - 'Net.WebClient'   # .NET class for web downloads
            - 'nop'    # NoProfile parameter abbreviation
            - 'w hidden'    # WindowStyle Hidden abbreviation
            - 'windowstyle hidden'    # Full parameter to hide window
            - 'encodedcommand'    # Encoded command for obfuscation
    condition: selection_registry and base_components and suspicious_indicators
falsepositives:
    - Unknown
level: high
