name: Validate Sigma rules

on: [push, pull_request, merge_group, workflow_dispatch]

env:
  SIGMA_RULE_SCHEMA_VERSION: v2.1.0

jobs:
  sigma-rules-validator:
    runs-on: ubuntu-latest
    steps:
      - name: Validate Sigma rules
        uses: SigmaHQ/sigma-rules-validator@66a5abe3fb6d13ac203ded42045580845c9c5534 # v1
        with:
          paths: |-
            ./rules
            ./rules-compliance
            ./rules-dfir
            ./rules-emerging-threats
            ./rules-placeholder
            ./rules-threat-hunting
          schemaURL: https://raw.githubusercontent.com/SigmaHQ/sigma-specification/refs/tags/${{ env.SIGMA_RULE_SCHEMA_VERSION }}/json-schema/sigma-detection-rule-schema.json
