name: Validate Sigma rules

on: [push, pull_request, merge_group, workflow_dispatch]

jobs:
  sigma-rules-validator:
    runs-on: ubuntu-latest
    steps:
      - name: Validate Sigma rules
        uses: SigmaHQ/sigma-rules-validator@v1
        with:
          paths: |-
            ./rules
            ./rules-compliance
            ./rules-dfir
            ./rules-emerging-threats
            ./rules-placeholder
            ./rules-threat-hunting
          schemaURL: https://raw.githubusercontent.com/SigmaHQ/sigma-specification/refs/tags/v2.1.0/json-schema/sigma-detection-rule-schema.json
