title: Suspicious Child Process of ConfigurationRemotingServer
id: 21de4d86-addc-4299-9e34-47a3616fe676
status: experimental
description: |
    Detects suspicious child processes spawned by ConfigurationRemotingServer.exe.
    Tools such as DSCourier abuse Windows Desired State Configuration (DSC) to execute arbitrary code — once a malicious DSC configuration is processed by ConfigurationRemotingServer.exe,
    an attacker-controlled PowerShell payload can spawn reconnaissance or post-exploitation tools as child processes.
references:
    - https://dylansec.com/DSCourier/
    - https://github.com/DylanDavis1/DSCourier
    - https://eclipsesec.com/posts/DSCourier/
    - https://www.zerosalarium.com/2024/12/LOLBIN%20WinGet%20execute%20PowerShell%20script.html
author: Richard Roy (@unresolvedhost), Swachchhanda Shrawan Poudel (Nextron Systems)
date: 2026-04-21
tags:
    - attack.execution
    - attack.t1059
    - attack.stealth
    - attack.t1218
logsource:
    category: process_creation
    product: windows
detection:
    selection:
        ParentImage|endswith: '\ConfigurationRemotingServer.exe'
        Image|endswith:
            - '\bitsadmin.exe'
            - '\certutil.exe'
            - '\cmd.exe'
            - '\cscript.exe'
            - '\curl.exe'
            - '\hostname.exe'
            - '\ipconfig.exe'
            - '\msbuild.exe'
            - '\mshta.exe'
            - '\net.exe'
            - '\net1.exe'
            - '\powershell.exe'
            - '\pwsh.exe'
            - '\regsvr32.exe'
            - '\rundll32.exe'
            - '\systeminfo.exe'
            - '\whoami.exe'
            - '\wmic.exe'
            - '\wscript.exe'
    condition: selection
falsepositives:
    - Unknown
level: high
